// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	killSidecar: () => __TAURI_INVOKE<void>("kill_sidecar"),
	installCli: () => __TAURI_INVOKE<string>("install_cli"),
	awaitInitialization: (events: Channel) => __TAURI_INVOKE<ServerReadyData>("await_initialization", { events }),
	getDefaultServerUrl: () => __TAURI_INVOKE<string | null>("get_default_server_url"),
	setDefaultServerUrl: (url: string | null) => __TAURI_INVOKE<null>("set_default_server_url", { url }),
	getWslConfig: () => __TAURI_INVOKE<WslConfig>("get_wsl_config"),
	setWslConfig: (config: WslConfig) => __TAURI_INVOKE<null>("set_wsl_config", { config }),
	getDisplayBackend: () => __TAURI_INVOKE<"wayland" | "auto" | null>("get_display_backend"),
	setDisplayBackend: (backend: LinuxDisplayBackend) => __TAURI_INVOKE<null>("set_display_backend", { backend }),
	parseMarkdownCommand: (markdown: string) => __TAURI_INVOKE<string>("parse_markdown_command", { markdown }),
	checkAppExists: (appName: string) => __TAURI_INVOKE<boolean>("check_app_exists", { appName }),
	wslPath: (path: string, mode: "windows" | "linux" | null) => __TAURI_INVOKE<string>("wsl_path", { path, mode }),
	resolveAppPath: (appName: string) => __TAURI_INVOKE<string | null>("resolve_app_path", { appName }),
	openPath: (path: string, appName: string | null) => __TAURI_INVOKE<null>("open_path", { path, appName }),
	installGitMacos: () => __TAURI_INVOKE<InstallResult>("install_git_macos"),
	installGitWindows: () => __TAURI_INVOKE<InstallResult>("install_git_windows"),
	linuxInstallHint: (tool: string) => __TAURI_INVOKE<string>("linux_install_hint", { tool }),
	repairGpdVenv: () => __TAURI_INVOKE<null>("repair_gpd_venv"),
	installTectonic: () => __TAURI_INVOKE<string>("install_tectonic"),
};

/** Events */
export const events = {
	gpdFirstRunComplete: makeEvent<GpdFirstRunComplete>("gpd-first-run-complete"),
	loadingWindowComplete: makeEvent<LoadingWindowComplete>("loading-window-complete"),
	sqliteMigrationProgress: makeEvent<SqliteMigrationProgress>("sqlite-migration-progress"),
	tectonicDownloadProgress: makeEvent<TectonicDownloadProgress>("tectonic-download-progress"),
};

/* Types */
/**
 * Emitted once, after a successful GPD first-run setup, so the frontend can
 * show an informational toast about where files were installed.
 */
export type GpdFirstRunComplete = null;

export type InitStep = { phase: "server_waiting" } | { phase: "sqlite_waiting" } | { phase: "gpd_setup" } | { phase: "done" };

/**
 * Result returned to the frontend after an install command is spawned.
 */
export type InstallResult = {
		
	/**
 * Whether the installer was launched successfully. This does not
 * guarantee the install finished — some installers detach and run
 * out-of-band (e.g. xcode-select's GUI prompt).
 */
launched: boolean,
		
	/**
 * Human-readable message describing what happened.
 */
message: string,
	};

export type LinuxDisplayBackend = "wayland" | "auto";

export type LoadingWindowComplete = null;

export type ServerReadyData = {
		url: string,
		username: string | null,
		password: string | null,
	};

export type SqliteMigrationProgress = { type: "InProgress"; value: number } | { type: "Done" };

/**
 * Progress payload emitted under the `tectonic-download-progress` event
 * while the Tectonic archive is being streamed from GitHub.
 * 
 * Fields are typed as `f64` (rather than `u64`) because TypeScript's
 * `number` is a double and the specta TypeScript exporter forbids
 * `BigInt`-backed integers by default. Tectonic archives are ~20-30 MB,
 * which is well inside the safe-integer range for `f64`.
 */
export type TectonicDownloadProgress = {
		
	/**
 * Bytes downloaded so far.
 */
loaded: number,
		
	/**
 * Total bytes advertised by the server, or 0 if unknown.
 */
total: number,
	};

export type WslConfig = {
		enabled: boolean,
	};

export type WslPathMode = "windows" | "linux";

/* Tauri Specta runtime */
function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: (payload: T) => __TAURI_EVENT.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: (payload: T) => target.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

